---
trigger: triage
title: Triage
description: Triage an incoming issue to update content with a visibility, impact, urgency, effort, and priority.
surfaces:
  - issue
steps:
  - type: form
    style: modal
    body:
    - type: markdown
      attributes:
        value: xxx
        text: |
          ## Triage

          Triage an incoming issue to determine its priority score. The score is a value from 0-5.
          A priority of 0 is given the most importance and 5 is the least.
    - type: dropdown
      attributes:
        id: visibility
        label: Visibility
        description: |
          Highly visible issues are more important.
        options:
          - label: Low visibility
            value: Low visibility
          - label: High visibility
            value: High visibility
    - type: dropdown
      attributes:
        id: impact
        label: Impact
        description: |
          High impact issues are more important.
        options:
          - label: Low impact
            value: Low impact
          - label: High impact
            value: High impact
    - type: dropdown
      attributes:
        id: effort
        label: Effort
        description: |
          Low effort issues are more important.
        options:
          - label: High effort
            value: High effort
          - label: Low effort
            value: Low effort
    - type: dropdown
      attributes:
        id: urgency
        label: Urgency
        description: |
          High urgency issues are more important.
        options:
          - label: Low urgency
            value: Low urgency
          - label: Medium urgency
            value: Medium urgency
          - label: High urgency
            value: High urgency
  - type: fill
    template_path: .github/commands/triage.liquid
